import "server-only"
import type { Locale } from "./config"
import { DEFAULT_LOCALE } from "./config"
import en from "./dictionaries/en.json"

// `en.json` is the canonical shape; every other locale is a (possibly partial)
// machine translation generated by `scripts/translate-ui.ts`.
export type Dictionary = typeof en

// Generated locales may be partial — not just whole namespaces missing, but keys
// missing *within* a namespace (a new en key not yet translated). deepMerge
// backfills from en, so type them as a deep partial.
type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] }

const loaders: Record<Locale, () => Promise<{ default: DeepPartial<Dictionary> }>> = {
  en: () => Promise.resolve({ default: en }),
  ja: () => import("./dictionaries/ja.json") as Promise<{ default: DeepPartial<Dictionary> }>,
  ko: () => import("./dictionaries/ko.json") as Promise<{ default: DeepPartial<Dictionary> }>,
  ar: () => import("./dictionaries/ar.json") as Promise<{ default: DeepPartial<Dictionary> }>,
  ru: () => import("./dictionaries/ru.json") as Promise<{ default: DeepPartial<Dictionary> }>,
  hi: () => import("./dictionaries/hi.json") as Promise<{ default: DeepPartial<Dictionary> }>,
  zh: () => import("./dictionaries/zh.json") as Promise<{ default: DeepPartial<Dictionary> }>,
  el: () => import("./dictionaries/el.json") as Promise<{ default: DeepPartial<Dictionary> }>,
  he: () => import("./dictionaries/he.json") as Promise<{ default: DeepPartial<Dictionary> }>,
  th: () => import("./dictionaries/th.json") as Promise<{ default: DeepPartial<Dictionary> }>,
}

export async function getDictionary(locale: Locale): Promise<Dictionary> {
  if (locale === DEFAULT_LOCALE) return en
  try {
    const mod = await loaders[locale]()
    // shallow-merge over en so any key missing from a generated file falls back
    return deepMerge(en, mod.default)
  } catch {
    return en
  }
}

// English is the canonical source — `en` always exists; this just backfills holes.
// Every namespace is a flat string map, so treat it uniformly here.
type FlatNs = Record<string, string>
function deepMerge(base: Dictionary, over: DeepPartial<Dictionary>): Dictionary {
  const b = base as Record<string, FlatNs>
  const o = over as Record<string, FlatNs>
  const out: Record<string, FlatNs> = {}
  for (const k of Object.keys(b)) {
    out[k] = { ...b[k], ...(o[k] ?? {}) }
  }
  return out as Dictionary
}
